name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c6f37ab5fa8cb7839a369520248fc882ddf7c87f346e1cd56313464731a65ac"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
