name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fb5cfea1ecb39ed5a2f50a5a5e5a1edbd93c4a658c558ff01ef13012c54ba68"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
