name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e7e11bfc0ab9b64347c95ce15faaedabc31c63d15b666e2d801976a954581dc"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
