name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7e071bf52a2edf8705458eac3f3e0ee619af20df42c1f39ddb4cb0936c9f8ca"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
