name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72c5b54077c69676a13dc0cd0651d51d66053a412fe64acbcb5e1318c24e4aef"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
