name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af6d03d0d8e1e94f0090c56ac121d1dc44a66e1618f2e8e840c23730c796d66"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
