name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "218beb1fcb7e0ec6bd6cb2e8200dfaf6717890e72ea54932bdb13e90cdac87c4"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
