name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "390cc92993c510a4ec53e8b48eac0acc94a75346fcc41b4c606031e0e0ac6d4c"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
