name = "Theseus S2"
author = "Explosivejoe, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e3001e10b1182d30791d31315526884e485d2845479877ae389ef796cb0f90b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
